# Generated by Django 5.0.6 on 2024-05-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_remove_property_location_project_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='floor',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='heating_option',
            field=models.CharField(choices=[('none', 'None'), ('gas', 'Gas'), ('electric', 'Electric'), ('oil', 'Oil'), ('none', 'None')], default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='master_count',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='unit_number',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
