# Generated by Django 5.0.6 on 2024-06-10 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_alter_project_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='image_2d',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='image_3d',
        ),
    ]
