# Generated by Django 5.0.6 on 2024-05-23 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_rename_video_propertyvideo_projectvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectvideo',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='propertyvideo',
            name='uploaded_at',
        ),
    ]
