# Generated by Django 5.0.6 on 2024-05-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_remove_projectvideo_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
