# Generated by Django 5.0.6 on 2024-06-12 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0010_remove_property_category_property_pool_count_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
