# Generated by Django 5.0.6 on 2024-05-28 10:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0012_project_offer_property_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='facilities',
            field=models.ManyToManyField(related_name='projects', to='location.facility'),
        ),
        migrations.AlterField(
            model_name='project',
            name='offer',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='offer',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
