# Generated by Django 5.0.6 on 2024-06-04 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0014_neighborhood_project_neighborhood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='city',
        ),
    ]
