# Generated by Django 5.0.6 on 2024-06-29 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0016_rename_city_img_city_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='img',
            new_name='city_img',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='img',
            new_name='country_img',
        ),
        migrations.RenameField(
            model_name='neighborhood',
            old_name='img',
            new_name='neighborhood_img',
        ),
        migrations.RenameField(
            model_name='projectbuildingplan',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='projectimage',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='propertybuildingplan',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='propertyimage',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='propertyoutwardview',
            old_name='img',
            new_name='image',
        ),
    ]
