# Generated by Django 5.0.6 on 2024-05-21 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentinfo',
            name='approval_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buyerpersonalinfo',
            name='approval_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerpersonalinfo',
            name='approval_status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Technical', 'Technical Issue'), ('Billing', 'Billing Inquiry'), ('General', 'General Support')], max_length=100, verbose_name='Subject')),
                ('description', models.TextField(verbose_name='Description')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Response')),
                ('status', models.CharField(choices=[('New', 'New'), ('InProgress', 'In Progress'), ('Closed', 'Closed')], default='New', max_length=20, verbose_name='Ticket Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Assigned User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_tickets', to=settings.AUTH_USER_MODEL, verbose_name='User Who Submitted')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
    ]
