# Generated by Django 5.0.6 on 2024-05-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_agentinfo_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='department',
            field=models.CharField(choices=[('IT', 'IT Department'), ('HR', 'Human Resources'), ('Finance', 'Finance Department'), ('Support', 'Customer Support')], default='IT', max_length=50, verbose_name='Department'),
            preserve_default=False,
        ),
    ]
