# Generated by Django 5.0.6 on 2024-06-06 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_device_access_token_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='device',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='device',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='device',
            name='updated_at',
        ),
    ]
