# Generated by Django 5.0.6 on 2024-05-26 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_agentinfo_created_at_agentinfo_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralcode',
            name='user',
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='agent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to=settings.AUTH_USER_MODEL),
        ),
    ]
