# Generated by Django 5.0.6 on 2024-05-28 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_referralcode_user_alter_referralcode_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
