# Generated by Django 5.0.6 on 2024-05-30 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentinfo',
            name='agent_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agentinfo',
            name='biometric',
            field=models.ImageField(null=True, unique=True, upload_to='biometric_images/'),
        ),
        migrations.AlterField(
            model_name='agentinfo',
            name='business_card',
            field=models.ImageField(null=True, unique=True, upload_to='business_card_images/'),
        ),
        migrations.AlterField(
            model_name='agentinfo',
            name='company_address',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='agentinfo',
            name='company_email',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='agentinfo',
            name='company_name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='agentinfo',
            name='company_phone_number',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='agentinfo',
            name='id_card',
            field=models.ImageField(null=True, unique=True, upload_to='id_card_images/'),
        ),
    ]
