# Generated by Django 5.0.6 on 2024-05-30 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_agentinfo_agent_user_alter_agentinfo_biometric_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentinfo',
            name='agent_user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agent_info', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buyerpersonalinfo',
            name='biometric',
            field=models.ImageField(null=True, unique=True, upload_to='biometric_images/'),
        ),
        migrations.AlterField(
            model_name='buyerpersonalinfo',
            name='birth_certificate',
            field=models.ImageField(null=True, unique=True, upload_to='birth_certificate_images/'),
        ),
        migrations.AlterField(
            model_name='buyerpersonalinfo',
            name='buyer_agreement',
            field=models.ImageField(null=True, unique=True, upload_to='buyer_aggrement_images/'),
        ),
        migrations.AlterField(
            model_name='buyerpersonalinfo',
            name='elec_bill',
            field=models.ImageField(null=True, unique=True, upload_to='elec_bill_images/'),
        ),
        migrations.AlterField(
            model_name='buyerpersonalinfo',
            name='full_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='buyerpersonalinfo',
            name='id_or_driver_license',
            field=models.ImageField(null=True, unique=True, upload_to='id_or_driver_license_images/'),
        ),
        migrations.AlterField(
            model_name='buyerpersonalinfo',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married')], max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='buyerpersonalinfo',
            name='postal_address',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sellerpersonalinfo',
            name='biometric',
            field=models.ImageField(null=True, unique=True, upload_to='biometric_images/'),
        ),
        migrations.AlterField(
            model_name='sellerpersonalinfo',
            name='birth_certificate',
            field=models.ImageField(null=True, unique=True, upload_to='birth_certificate_images/'),
        ),
        migrations.AlterField(
            model_name='sellerpersonalinfo',
            name='elec_bill',
            field=models.ImageField(null=True, unique=True, upload_to='elec_bill_images/'),
        ),
        migrations.AlterField(
            model_name='sellerpersonalinfo',
            name='full_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sellerpersonalinfo',
            name='id_or_driver_license',
            field=models.ImageField(null=True, unique=True, upload_to='id_or_driver_license_images/'),
        ),
        migrations.AlterField(
            model_name='sellerpersonalinfo',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married')], max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sellerpersonalinfo',
            name='passport',
            field=models.ImageField(null=True, unique=True, upload_to='passport_images/'),
        ),
        migrations.AlterField(
            model_name='sellerpersonalinfo',
            name='postal_address',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sellerpersonalinfo',
            name='seller_agreement',
            field=models.ImageField(null=True, unique=True, upload_to='seller_aggrement_images/'),
        ),
    ]
