version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn OnEarth.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_files_volume:/usr/src/app/staticfiles
      - media_files_volume:/usr/src/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./app/.env.prod
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db
    ports:
      - "5432:5432"

  nginx:
    build: ./nginx
    volumes:
      - static_files_volume:/home/app/web/staticfiles
      - media_files_volume:/home/app/web/media
    ports:
      - "443:443"
    depends_on:
      - web

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data_volume:/data

volumes:
  postgres_data_volume:
  static_files_volume:
  media_files_volume:
  redis_data_volume:
