# Generated by Django 5.0.6 on 2024-06-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinginfo',
            name='extra_fee_description',
            field=models.TextField(default='extra fee description'),
            preserve_default=False,
        ),
    ]
