# Generated by Django 5.0.6 on 2024-07-10 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_shippinginfo_extra_fee_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nft',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='shippinginfo',
            options={'ordering': ['id']},
        ),
    ]
