# Generated by Django 5.0.6 on 2024-07-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_remove_shippinginfo_payoff_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinginfo',
            name='payoff_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
