# Generated by Django 5.0.6 on 2024-05-23 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinginfo',
            name='connections',
            field=models.DecimalField(decimal_places=2, default=236, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='extra_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='title_deed_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=11000, max_digits=10),
        ),
    ]
