# Generated by Django 5.0.6 on 2024-05-26 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_alter_shippinginfo_connections_and_more'),
        ('location', '0010_alter_property_floor_alter_property_unit_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_id', models.CharField(max_length=100, unique=True)),
                ('owner', models.CharField(max_length=100)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nfts', to='location.property')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
