# Generated by Django 5.0.6 on 2024-05-26 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_payment_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
