# Generated by Django 5.0.6 on 2024-06-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_project_latitude_alter_project_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='floor',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='unit_number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
