# Generated by Django 5.0.6 on 2024-06-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_property_floor_alter_property_unit_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='address',
            field=models.TextField(),
        ),
    ]
