# Generated by Django 5.0.6 on 2024-06-10 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_alter_projectimage_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(default='', upload_to='project_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.project'),
        ),
        migrations.AlterField(
            model_name='property',
            name='heating_option',
            field=models.CharField(choices=[('none', 'None'), ('heating stoves', 'Heating Stoves'), ('natural gas stove', 'Natural Gas Stove'), ('room heater', 'Room Heater'), ('central heating', 'Central Heating'), ('central heating (share meter)', 'Central Heating (Share Meter)'), ('central heating boiler (electric)', 'Central Heating Boiler (Electric)'), ('central heating boilers (natural gas)', 'Central Heating Boilers (Natural Gas)'), ('floor heating', 'Floor Heating'), ('air conditioning', 'Air Conditioning'), ('fan coil unit', 'Fan Coil Unit'), ('solar energy', 'Solar Energy'), ('elektrikli radyator', 'Elektrikli Radyator')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(default='', upload_to='Property_images/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProjectBuildingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_image', models.ImageField(upload_to='project_plan_images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyBuildingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_image', models.ImageField(upload_to='property_plan_images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.property')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyOutwardView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_image', models.ImageField(upload_to='property_outward_images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.property')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
