# Generated by Django 5.0.6 on 2024-06-10 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_alter_projectimage_image_alter_projectimage_project_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectbuildingplan',
            old_name='plan_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='propertybuildingplan',
            old_name='plan_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='propertyoutwardview',
            old_name='plan_image',
            new_name='image',
        ),
    ]
