# Generated by Django 5.0.6 on 2024-06-12 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_rename_plan_image_projectbuildingplan_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='location.city'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='neighborhood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='location.neighborhood'),
            preserve_default=False,
        ),
    ]
