# Generated by Django 5.0.6 on 2024-06-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0011_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='has_gym',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='has_meeting_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='has_music_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='has_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='has_party_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='has_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='has_security',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='has_spa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='has_theater',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='has_yoga_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='roofed_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='roofed_pool',
            field=models.BooleanField(default=False),
        ),
    ]
