# Generated by Django 5.0.6 on 2024-06-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0012_project_has_gym_project_has_meeting_room_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('home', 'Home'), ('apartment', 'Apartment'), ('villas', 'Villas'), ('penthouse', 'Penthouse'), ('super luxury', 'Super Luxury')], max_length=50, unique=True)),
            ],
        ),
    ]
