# Generated by Django 5.0.6 on 2024-06-12 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0013_propertycategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='location.propertycategory'),
            preserve_default=False,
        ),
    ]
