# Generated by Django 5.0.6 on 2024-06-28 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0014_property_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='facilities',
        ),
        migrations.AlterField(
            model_name='project',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='location.city'),
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
    ]
