# Generated by Django 5.0.6 on 2024-07-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0017_rename_img_city_city_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='living_room_count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, choices=[('studio', 'Studio'), ('duplex', 'Duplex')], default='studio', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='parking_space_count',
            field=models.IntegerField(default=1),
        ),
    ]
