# Generated by Django 5.0.6 on 2024-07-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0018_property_living_room_count_property_property_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_type',
        ),
        migrations.AlterField(
            model_name='propertycategory',
            name='name',
            field=models.CharField(choices=[('Duplex', 'Duplex'), ('Studio', 'Studio')], max_length=50, unique=True),
        ),
    ]
