# Generated by Django 5.0.6 on 2024-07-07 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0019_remove_property_property_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='floor_count',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='property',
            name='has_balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_bathroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_bedroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_dining_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_kitchen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_living_room',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LocationFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=255)),
                ('feature_time_in_minutes', models.IntegerField(default=5)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_features', to='location.project')),
            ],
        ),
    ]
