# Generated by Django 5.0.6 on 2024-07-07 07:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0020_project_floor_count_property_has_balcony_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationfeature',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationfeature',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
