# Generated by Django 5.0.6 on 2024-07-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0021_locationfeature_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='apartment_type_count',
            field=models.IntegerField(default=2),
        ),
    ]
