# Generated by Django 5.0.6 on 2024-07-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0023_remove_property_category_alter_banner_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertyBuildingPlan',
            new_name='PropertyBuildingPlanImages',
        ),
        migrations.AddField(
            model_name='project',
            name='property_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='plan_type',
            field=models.CharField(default='Studio', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PropertyOutwardView',
        ),
    ]
