# Generated by Django 5.0.6 on 2024-07-11 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0024_rename_propertybuildingplan_propertybuildingplanimages_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='balcony_count',
            new_name='living_rooms',
        ),
        migrations.RemoveField(
            model_name='project',
            name='gym_count',
        ),
        migrations.RemoveField(
            model_name='project',
            name='kids_swimming_pool_count',
        ),
        migrations.RemoveField(
            model_name='project',
            name='landscaped_gardens_count',
        ),
        migrations.RemoveField(
            model_name='project',
            name='large_lifts',
        ),
        migrations.RemoveField(
            model_name='project',
            name='meeting_room_count',
        ),
        migrations.RemoveField(
            model_name='project',
            name='music_room_count',
        ),
        migrations.RemoveField(
            model_name='project',
            name='parking_count',
        ),
        migrations.RemoveField(
            model_name='project',
            name='party_room_count',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pool_count',
        ),
        migrations.RemoveField(
            model_name='project',
            name='retail_areas_count',
        ),
        migrations.RemoveField(
            model_name='project',
            name='roofed_parking_count',
        ),
        migrations.RemoveField(
            model_name='project',
            name='roofed_pool_count',
        ),
        migrations.RemoveField(
            model_name='project',
            name='security_count',
        ),
        migrations.RemoveField(
            model_name='project',
            name='spa_count',
        ),
        migrations.RemoveField(
            model_name='project',
            name='theater_count',
        ),
        migrations.RemoveField(
            model_name='project',
            name='yoga_room_count',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='closet_count',
        ),
        migrations.RemoveField(
            model_name='property',
            name='is_open_kichen',
        ),
        migrations.RemoveField(
            model_name='property',
            name='living_room_count',
        ),
        migrations.RemoveField(
            model_name='property',
            name='lundry_count',
        ),
        migrations.RemoveField(
            model_name='property',
            name='master_count',
        ),
        migrations.RemoveField(
            model_name='property',
            name='parking_space_count',
        ),
        migrations.RemoveField(
            model_name='property',
            name='pool_count',
        ),
        migrations.RemoveField(
            model_name='property',
            name='tub_count',
        ),
        migrations.CreateModel(
            name='ProjectFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('count', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.property')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('count', models.IntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.property')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
