# Generated by Django 5.0.6 on 2024-07-11 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0025_rename_balcony_count_property_living_rooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfacilities',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectfacilities', to='location.property'),
        ),
        migrations.AlterField(
            model_name='propertyfacilities',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propertyfacilities', to='location.property'),
        ),
    ]
