# Generated by Django 5.0.6 on 2024-07-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0027_alter_projectdetails_levels_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyfacilities',
            name='property',
        ),
        migrations.AddField(
            model_name='propertyfacilities',
            name='properties',
            field=models.ManyToManyField(related_name='property_facilities', to='location.property'),
        ),
    ]
