# Generated by Django 5.0.6 on 2024-07-12 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0028_remove_propertyfacilities_property_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='project',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='location.project'),
            preserve_default=False,
        ),
    ]
