# Generated by Django 5.0.6 on 2024-07-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0029_alter_property_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='first_floor',
        ),
        migrations.RemoveField(
            model_name='property',
            name='first_unit_number',
        ),
        migrations.RemoveField(
            model_name='property',
            name='last_floor',
        ),
        migrations.RemoveField(
            model_name='property',
            name='last_unit_number',
        ),
        migrations.AddField(
            model_name='property',
            name='floor_numbers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='unit_numbers_per_floor',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
