# Generated by Django 5.0.6 on 2024-07-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0030_remove_property_first_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gym',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='land_scape_green_garden',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='metting_room',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='parking',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='pool',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='security',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='balcony',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='bathtub',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='guest_toliet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='is_open_kitchen',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='landry',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='master',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='wardrop',
            field=models.IntegerField(default=0),
        ),
    ]
