# Generated by Django 5.0.6 on 2024-07-13 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0030_remove_property_first_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_details', to='location.project'),
        ),
    ]
