# Generated by Django 5.0.6 on 2024-07-13 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0031_alter_projectdetails_project'),
        ('location', '0031_project_gym_project_land_scape_green_garden_and_more'),
    ]

    operations = [
    ]
