# Generated by Django 5.0.6 on 2024-07-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0032_merge_20240713_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='floors',
            field=models.IntegerField(default=0),
        ),
    ]
