# Generated by Django 5.0.6 on 2024-07-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0033_project_floors'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cheapest_property_type',
            field=models.CharField(default='studio', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='has_promotion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='the_most_expensive_property_type',
            field=models.CharField(default='penthouse', max_length=50),
            preserve_default=False,
        ),
    ]
