# Generated by Django 5.0.6 on 2024-07-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0034_project_cheapest_property_type_project_has_promotion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='balcony_metrage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
