# Generated by Django 5.0.6 on 2024-07-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0035_property_balcony_metrage'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationfeature',
            name='feature_distance',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='master_plan_img',
            field=models.ImageField(blank=True, null=True, upload_to='master_plan_images/'),
        ),
        migrations.AlterField(
            model_name='locationfeature',
            name='type',
            field=models.CharField(blank=True, choices=[('Walk', 'walk'), ('Car', 'car'), ('Km', 'km')], max_length=50, null=True),
        ),
    ]
