# Generated by Django 5.0.6 on 2024-07-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0036_locationfeature_feature_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='villa_numbers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
