# Generated by Django 5.0.6 on 2024-07-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0037_property_villa_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationfeature',
            name='feature_distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locationfeature',
            name='feature_time_in_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locationfeature',
            name='type',
            field=models.CharField(blank=True, choices=[('Walk', 'walk'), ('Car', 'car'), ('Km', 'km')], default='km', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_per_nft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
