# Generated by Django 5.0.6 on 2024-07-23 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0038_alter_locationfeature_feature_distance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='property',
            name='longitude',
        ),
    ]
