# Generated by Django 5.0.6 on 2024-07-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0039_remove_property_latitude_remove_property_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('Apartment', 'apartment'), ('Villa', 'villa')], default='apartment', max_length=50),
        ),
    ]
