# Generated by Django 5.0.6 on 2024-07-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0040_property_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='master_plan_img',
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('villa', 'Villa')], default='apartment', max_length=50),
        ),
    ]
