# Generated by Django 5.0.6 on 2024-06-05 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passport', models.ImageField(null=True, unique=True, upload_to='passport_images/')),
                ('passport_approval_status', models.CharField(choices=[('New', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20, verbose_name='Passport approval Status')),
                ('biometric', models.ImageField(null=True, unique=True, upload_to='biometric_images/')),
                ('biometric_approval_status', models.CharField(choices=[('New', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20, verbose_name='biometric approval Status')),
                ('basic_approval_status', models.CharField(choices=[('New', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20, verbose_name='Basic info approval Status')),
                ('approval_status', models.CharField(choices=[('New', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20, verbose_name='َApproval Status')),
                ('company_name', models.CharField(max_length=255, null=True, unique=True)),
                ('company_address', models.CharField(max_length=255, null=True, unique=True)),
                ('company_email', models.EmailField(max_length=255, null=True, unique=True)),
                ('company_phone_number', models.CharField(max_length=11, null=True, unique=True)),
                ('business_card', models.ImageField(null=True, unique=True, upload_to='business_card_images/')),
                ('business_card_approval_status', models.CharField(choices=[('New', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20, verbose_name='Business card approval Status')),
                ('id_card', models.ImageField(null=True, unique=True, upload_to='id_card_images/')),
                ('id_card_approval_status', models.CharField(choices=[('New', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20, verbose_name='ID card approval Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_seller', models.BooleanField(default=False)),
                ('is_buyer', models.BooleanField(default=False)),
                ('is_agent', models.BooleanField(default=False)),
                ('is_guest', models.BooleanField(default=True)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuyerPersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passport', models.ImageField(null=True, unique=True, upload_to='passport_images/')),
                ('passport_approval_status', models.CharField(choices=[('New', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20, verbose_name='Passport approval Status')),
                ('biometric', models.ImageField(null=True, unique=True, upload_to='biometric_images/')),
                ('biometric_approval_status', models.CharField(choices=[('New', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20, verbose_name='biometric approval Status')),
                ('basic_approval_status', models.CharField(choices=[('New', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20, verbose_name='Basic info approval Status')),
                ('approval_status', models.CharField(choices=[('New', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20, verbose_name='َApproval Status')),
                ('full_name', models.CharField(max_length=100, null=True, unique=True)),
                ('postal_address', models.TextField(null=True, unique=True)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married')], max_length=20, null=True, unique=True)),
                ('marriage_contract', models.ImageField(blank=True, null=True, upload_to='marriage_contract_images/')),
                ('elec_bill', models.ImageField(null=True, unique=True, upload_to='elec_bill_images/')),
                ('elec_bill_approval_status', models.CharField(choices=[('New', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20, verbose_name='Elec bill approval Status')),
                ('birth_certificate', models.ImageField(null=True, unique=True, upload_to='birth_certificate_images/')),
                ('birth_certificate_approval_status', models.CharField(choices=[('New', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20, verbose_name='Birth certificate approval Status')),
                ('id_or_driver_license', models.ImageField(null=True, unique=True, upload_to='id_or_driver_license_images/')),
                ('id_or_driver_license_approval_status', models.CharField(choices=[('New', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20, verbose_name='ID or driver license approval Status')),
                ('buyer_agreement', models.ImageField(null=True, unique=True, upload_to='buyer_aggrement_images/')),
                ('buyer_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_personal_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SellerPersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passport', models.ImageField(null=True, unique=True, upload_to='passport_images/')),
                ('passport_approval_status', models.CharField(choices=[('New', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20, verbose_name='Passport approval Status')),
                ('biometric', models.ImageField(null=True, unique=True, upload_to='biometric_images/')),
                ('biometric_approval_status', models.CharField(choices=[('New', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20, verbose_name='biometric approval Status')),
                ('basic_approval_status', models.CharField(choices=[('New', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20, verbose_name='Basic info approval Status')),
                ('approval_status', models.CharField(choices=[('New', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20, verbose_name='َApproval Status')),
                ('full_name', models.CharField(max_length=100, null=True, unique=True)),
                ('postal_address', models.TextField(null=True, unique=True)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married')], max_length=20, null=True, unique=True)),
                ('marriage_contract', models.ImageField(blank=True, null=True, upload_to='marriage_contract_images/')),
                ('elec_bill', models.ImageField(null=True, unique=True, upload_to='elec_bill_images/')),
                ('elec_bill_approval_status', models.CharField(choices=[('New', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20, verbose_name='Elec bill approval Status')),
                ('birth_certificate', models.ImageField(null=True, unique=True, upload_to='birth_certificate_images/')),
                ('birth_certificate_approval_status', models.CharField(choices=[('New', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20, verbose_name='Birth certificate approval Status')),
                ('id_or_driver_license', models.ImageField(null=True, unique=True, upload_to='id_or_driver_license_images/')),
                ('id_or_driver_license_approval_status', models.CharField(choices=[('New', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20, verbose_name='ID or driver license approval Status')),
                ('seller_agreement', models.ImageField(null=True, unique=True, upload_to='seller_aggrement_images/')),
                ('seller_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_personal_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(choices=[('Technical', 'Technical Issue'), ('Billing', 'Billing Inquiry'), ('General', 'General Support')], max_length=100, verbose_name='Subject')),
                ('description', models.TextField(verbose_name='Description')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Response')),
                ('status', models.CharField(choices=[('New', 'New'), ('InProgress', 'In Progress'), ('Closed', 'Closed')], default='New', max_length=20, verbose_name='Ticket Status')),
                ('department', models.CharField(choices=[('IT', 'IT Department'), ('HR', 'Human Resources'), ('Finance', 'Finance Department'), ('Support', 'Customer Support')], max_length=50, verbose_name='Department')),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Assigned User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_tickets', to=settings.AUTH_USER_MODEL, verbose_name='User Who Submitted')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
    ]
