# Generated by Django 5.0.6 on 2024-06-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentinfo',
            name='biometric',
            field=models.ImageField(blank=True, null=True, upload_to='biometric_images/'),
        ),
        migrations.AlterField(
            model_name='agentinfo',
            name='business_card',
            field=models.ImageField(blank=True, null=True, upload_to='business_card_images/'),
        ),
        migrations.AlterField(
            model_name='agentinfo',
            name='company_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agentinfo',
            name='company_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agentinfo',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agentinfo',
            name='company_phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='agentinfo',
            name='id_card',
            field=models.ImageField(blank=True, null=True, upload_to='id_card_images/'),
        ),
        migrations.AlterField(
            model_name='agentinfo',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to='passport_images/'),
        ),
        migrations.AlterField(
            model_name='buyerpersonalinfo',
            name='biometric',
            field=models.ImageField(blank=True, null=True, upload_to='biometric_images/'),
        ),
        migrations.AlterField(
            model_name='buyerpersonalinfo',
            name='birth_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='birth_certificate_images/'),
        ),
        migrations.AlterField(
            model_name='buyerpersonalinfo',
            name='buyer_agreement',
            field=models.ImageField(blank=True, null=True, upload_to='buyer_aggrement_images/'),
        ),
        migrations.AlterField(
            model_name='buyerpersonalinfo',
            name='elec_bill',
            field=models.ImageField(blank=True, null=True, upload_to='elec_bill_images/'),
        ),
        migrations.AlterField(
            model_name='buyerpersonalinfo',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyerpersonalinfo',
            name='id_or_driver_license',
            field=models.ImageField(blank=True, null=True, upload_to='id_or_driver_license_images/'),
        ),
        migrations.AlterField(
            model_name='buyerpersonalinfo',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='buyerpersonalinfo',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to='passport_images/'),
        ),
        migrations.AlterField(
            model_name='buyerpersonalinfo',
            name='postal_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellerpersonalinfo',
            name='biometric',
            field=models.ImageField(blank=True, null=True, upload_to='biometric_images/'),
        ),
        migrations.AlterField(
            model_name='sellerpersonalinfo',
            name='birth_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='birth_certificate_images/'),
        ),
        migrations.AlterField(
            model_name='sellerpersonalinfo',
            name='elec_bill',
            field=models.ImageField(blank=True, null=True, upload_to='elec_bill_images/'),
        ),
        migrations.AlterField(
            model_name='sellerpersonalinfo',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellerpersonalinfo',
            name='id_or_driver_license',
            field=models.ImageField(blank=True, null=True, upload_to='id_or_driver_license_images/'),
        ),
        migrations.AlterField(
            model_name='sellerpersonalinfo',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sellerpersonalinfo',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to='passport_images/'),
        ),
        migrations.AlterField(
            model_name='sellerpersonalinfo',
            name='postal_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellerpersonalinfo',
            name='seller_agreement',
            field=models.ImageField(blank=True, null=True, upload_to='seller_aggrement_images/'),
        ),
    ]
