# Generated by Django 5.0.6 on 2024-06-05 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_agentinfo_biometric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentinfo',
            name='agent_user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agent_info', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
