# Generated by Django 5.0.6 on 2024-06-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='access_token_id',
        ),
        migrations.RemoveField(
            model_name='device',
            name='refresh_token_id',
        ),
        migrations.AddField(
            model_name='device',
            name='access_token',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='refresh_token',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
