# Generated by Django 5.0.6 on 2024-06-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_device_created_at_device_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='refresh_token',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
