# Generated by Django 5.0.6 on 2024-07-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_device_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentinfo',
            name='basic_info_approval_status',
            field=models.CharField(choices=[('New', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20, verbose_name='Basic information approval Status'),
        ),
        migrations.AddField(
            model_name='buyerpersonalinfo',
            name='basic_info_approval_status',
            field=models.CharField(choices=[('New', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20, verbose_name='Basic information approval Status'),
        ),
        migrations.AddField(
            model_name='sellerpersonalinfo',
            name='basic_info_approval_status',
            field=models.CharField(choices=[('New', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20, verbose_name='Basic information approval Status'),
        ),
        migrations.AlterField(
            model_name='agentinfo',
            name='approval_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='buyerpersonalinfo',
            name='approval_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sellerpersonalinfo',
            name='approval_status',
            field=models.BooleanField(default=False),
        ),
    ]
