# Generated by Django 5.0.6 on 2024-07-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_agentinfo_basic_info_approval_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentinfo',
            name='basic_approval_status',
        ),
        migrations.RemoveField(
            model_name='agentinfo',
            name='business_card',
        ),
        migrations.RemoveField(
            model_name='agentinfo',
            name='business_card_approval_status',
        ),
        migrations.RemoveField(
            model_name='agentinfo',
            name='id_card',
        ),
        migrations.RemoveField(
            model_name='agentinfo',
            name='id_card_approval_status',
        ),
        migrations.RemoveField(
            model_name='agentinfo',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='agentinfo',
            name='passport_approval_status',
        ),
        migrations.RemoveField(
            model_name='buyerpersonalinfo',
            name='basic_approval_status',
        ),
        migrations.RemoveField(
            model_name='buyerpersonalinfo',
            name='buyer_agreement',
        ),
        migrations.RemoveField(
            model_name='buyerpersonalinfo',
            name='elec_bill',
        ),
        migrations.RemoveField(
            model_name='buyerpersonalinfo',
            name='elec_bill_approval_status',
        ),
        migrations.RemoveField(
            model_name='sellerpersonalinfo',
            name='basic_approval_status',
        ),
        migrations.RemoveField(
            model_name='sellerpersonalinfo',
            name='birth_certificate_approval_status',
        ),
        migrations.RemoveField(
            model_name='sellerpersonalinfo',
            name='elec_bill',
        ),
        migrations.RemoveField(
            model_name='sellerpersonalinfo',
            name='elec_bill_approval_status',
        ),
        migrations.RemoveField(
            model_name='sellerpersonalinfo',
            name='seller_agreement',
        ),
        migrations.AddField(
            model_name='agentinfo',
            name='aggrement',
            field=models.ImageField(blank=True, null=True, upload_to='aggrement_images/'),
        ),
        migrations.AddField(
            model_name='agentinfo',
            name='aggrement_approval_status',
            field=models.CharField(choices=[('New', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20, verbose_name='aggrement approval Status'),
        ),
        migrations.AddField(
            model_name='agentinfo',
            name='birth_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='birth_certificate_images/'),
        ),
        migrations.AddField(
            model_name='agentinfo',
            name='birth_certificate_approval_status',
            field=models.CharField(choices=[('New', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20, verbose_name='Birth certificate approval Status'),
        ),
        migrations.AddField(
            model_name='agentinfo',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agentinfo',
            name='id_card_or_passport',
            field=models.ImageField(blank=True, null=True, upload_to='id_card_or_passport_images/'),
        ),
        migrations.AddField(
            model_name='agentinfo',
            name='id_card_or_passport_approval_status',
            field=models.CharField(choices=[('New', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20, verbose_name='ID card or passport approval Status'),
        ),
        migrations.AddField(
            model_name='buyerpersonalinfo',
            name='aggrement',
            field=models.ImageField(blank=True, null=True, upload_to='aggrement_images/'),
        ),
        migrations.AddField(
            model_name='buyerpersonalinfo',
            name='aggrement_approval_status',
            field=models.CharField(choices=[('New', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20, verbose_name='aggrement approval Status'),
        ),
        migrations.AddField(
            model_name='buyerpersonalinfo',
            name='birth_certificate_status',
            field=models.CharField(choices=[('New', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20, verbose_name='Passport approval Status'),
        ),
        migrations.AddField(
            model_name='sellerpersonalinfo',
            name='aggrement',
            field=models.ImageField(blank=True, null=True, upload_to='aggrement_images/'),
        ),
        migrations.AddField(
            model_name='sellerpersonalinfo',
            name='aggrement_approval_status',
            field=models.CharField(choices=[('New', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20, verbose_name='aggrement approval Status'),
        ),
        migrations.AddField(
            model_name='sellerpersonalinfo',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='background_images/'),
        ),
        migrations.AddField(
            model_name='sellerpersonalinfo',
            name='background_status',
            field=models.CharField(choices=[('New', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20, verbose_name='background approval Status'),
        ),
        migrations.AddField(
            model_name='sellerpersonalinfo',
            name='birth_certificate_status',
            field=models.CharField(choices=[('New', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20, verbose_name='Passport approval Status'),
        ),
        migrations.AlterField(
            model_name='agentinfo',
            name='approval_status',
            field=models.CharField(choices=[('New', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20, verbose_name='َApproval Status'),
        ),
        migrations.AlterField(
            model_name='buyerpersonalinfo',
            name='approval_status',
            field=models.CharField(choices=[('New', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20, verbose_name='َApproval Status'),
        ),
        migrations.AlterField(
            model_name='sellerpersonalinfo',
            name='approval_status',
            field=models.CharField(choices=[('New', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20, verbose_name='َApproval Status'),
        ),
    ]
