# Generated by Django 5.0.6 on 2024-07-10 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_agentinfo_business_card_buyerpersonalinfo_elec_bill_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='referralcode',
            options={'ordering': ['id']},
        ),
    ]
