# Generated by Django 5.0.6 on 2024-07-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_device_options_alter_referralcode_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerpersonalinfo',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='background_images/'),
        ),
        migrations.AddField(
            model_name='buyerpersonalinfo',
            name='background_status',
            field=models.CharField(choices=[('New', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20, verbose_name='background approval Status'),
        ),
    ]
